### ISSUE TITLE
Data

### ISSUE THREAD

**Issue by 110rangeeeee** [hawkiyc/WaveGAN_for_12_Leads_ECG_Signals#1]
Hello, could you please share some information about the data read from target_signals_dir? Specifically regarding files ending in .npz. Thank you.

**Comment by hawkiyc** [comment]
Hi, @110rangeeeee

Due to poor hardware, I only used part CODE 15% in this implementation. In this repository, I only use those signals with no arrhythmia and crop all signals to 7 seconds. You can access the dataset via the [OneDrive link](https://1drv.ms/u/s!ArQCikHAsFj6oPJoQY7h9rIggjoaug?e=YjNprR) on the main page of this repository. The shape for npz files is (N, 12, 4096). For more details about CODE 15%, you shall check info via [this link](https://zenodo.org/record/4916206).

**Comment by 110rangeeeee** [comment]
Hello, we can no longer use OneDrive here. Could you please share the link using a different method?

**Comment by hawkiyc** [comment]
> Hello, we can no longer use OneDrive here. Could you please share the link using a different method?

Oh, I don't have another Cloud Drive with enough space for the dataset. You can still get those data via [zenodo](https://zenodo.org/records/4916206), though they use HDF5 format. Please check details about the dataset via zenodo website.

You can load those hdf5 file with following code:

```
import h5py
r = h5py.File(f_name.hdf5, 'r')
idx, ecg = np.array(r['exam_id']),np.array(r['tracings'])
```
